-- CreateEnum
CREATE TYPE "SprintStatus" AS ENUM ('PAST', 'CURRENT', 'COMPLETED');

-- CreateTable
CREATE TABLE "UserStory" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "description" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UserStory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Sprint" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "goal" STRING NOT NULL,
    "status" "SprintStatus" NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Sprint_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_UserToUserStory" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_SprintToTask" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "_UserToUserStory_AB_unique" ON "_UserToUserStory"("A", "B");

-- CreateIndex
CREATE INDEX "_UserToUserStory_B_index" ON "_UserToUserStory"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_SprintToTask_AB_unique" ON "_SprintToTask"("A", "B");

-- CreateIndex
CREATE INDEX "_SprintToTask_B_index" ON "_SprintToTask"("B");

-- AddForeignKey
ALTER TABLE "_UserToUserStory" ADD CONSTRAINT "_UserToUserStory_A_fkey" FOREIGN KEY ("A") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_UserToUserStory" ADD CONSTRAINT "_UserToUserStory_B_fkey" FOREIGN KEY ("B") REFERENCES "UserStory"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_SprintToTask" ADD CONSTRAINT "_SprintToTask_A_fkey" FOREIGN KEY ("A") REFERENCES "Sprint"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_SprintToTask" ADD CONSTRAINT "_SprintToTask_B_fkey" FOREIGN KEY ("B") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;
